### ISSUE TITLE
 Unknown CMake command "CPMAddPackage" when building 

### ISSUE THREAD

**Issue by liuyx599** [pawelswoboda/RAMA#33]
hello, I downloaded the RAMA source code to the `/src/RAMA-master/RAMA-master` directory and then I executed the following command. Since I was using conda for package management, I activated my conda environment emseg beforehand
```bash
cd /src/RAMA-master/RAMA-master
python setup.py install
```
This resulted in the following error on the console, aside from the WARNING message, the obvious error is that the

```
CMake Error at CMakeLists.txt:41 (CPMAddPackage):
  Unknown CMake command "CPMAddPackage".
```

```
setup.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing RAMA.egg-info/PKG-INFO
writing dependency_links to RAMA.egg-info/dependency_links.txt
writing top-level names to RAMA.egg-info/top_level.txt
reading manifest file 'RAMA.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'RAMA.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
build_with_torch:OFF


Testing gcc...
...has version 10.5.0
Found suitable gcc/g++ version gcc g++
CMake Error at CMakeLists.txt:41 (CPMAddPackage):
  Unknown CMake command "CPMAddPackage".


-- Configuring incomplete, errors occurred!
See also "/src/RAMA-master/RAMA-master/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    setup(
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 33, in run
    self.build_extension(ext)
  File "setup.py", line 117, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/src/anaconda3/envs/emseg/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/src/RAMA-master/RAMA-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/src/RAMA-master/RAMA-master/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=/src/anaconda3/envs/emseg/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

My relative tools' version:
```
CUDA Version: 11.7 
gcc version 10.5.0
cmake version 3.16.3
pip 23.3.2 
```

**Comment by pawelswoboda** [comment]
Sorry, this was some temporary screw-up during development. I have fixed it and tested installing with pip and it should work now. You can also do

python -m pip install git+https://github.com/pawelswoboda/RAMA.git

to install RAMA.

**Comment by liuyx599** [comment]
Thanks for you reply, but there seems occur a new error about cuda.
Although my server host supports CUDA, can I install a CPU version? This will block out the CUDA messages
```
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting git+https://github.com/pawelswoboda/RAMA.git
  Cloning https://github.com/pawelswoboda/RAMA.git to /tmp/pip-req-build-_2qrs2c6
  Running command git clone --filter=blob:none --quiet https://github.com/pawelswoboda/RAMA.git /tmp/pip-req-build-_2qrs2c6
  Resolved https://github.com/pawelswoboda/RAMA.git to commit 6b3d287795418db6f84484310958ec32f07eb5b9
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: RAMA
  Building wheel for RAMA (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [207 lines of output]
      /tmp/pip-req-build-_2qrs2c6/setup.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      /src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_ext
      build_with_torch:OFF
      
      
      Testing gcc...
      ...has version 10.5.0
      Found suitable gcc/g++ version gcc g++
      -- The CXX compiler identification is GNU 10.5.0
      -- The CUDA compiler identification is NVIDIA 11.3.109
      -- Check for working CXX compiler: /usr/bin/g++
      -- Check for working CXX compiler: /usr/bin/g++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
      -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Downloading CPM.cmake to /tmp/pip-req-build-_2qrs2c6/build/temp.linux-x86_64-cpython-38/cmake/CPM_0.34.0.cmake
      -- CPM: adding package pybind11@ (master)
      -- pybind11 v2.12.0 dev1
      CMake Warning at build/temp.linux-x86_64-cpython-38/_deps/pybind11-src/tools/pybind11Common.cmake:153 (message):
        USE -DCMAKE_CXX_STANDARD=17 instead of PYBIND11_CPP_STANDARD
      Call Stack (most recent call first):
        build/temp.linux-x86_64-cpython-38/_deps/pybind11-src/CMakeLists.txt:237 (include)
      
      
      -- Found PythonInterp: /src/anaconda3/envs/emseg/bin/python (found suitable version "3.8.18", minimum required is "3.6")
      -- Found PythonLibs: /src/anaconda3/envs/emseg/lib/libpython3.8.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- CPM: adding package thrust@ (main)
      -- Found libcudacxx: /tmp/pip-req-build-_2qrs2c6/build/temp.linux-x86_64-cpython-38/_deps/thrust-src/dependencies/libcudacxx/lib/cmake/libcudacxx/libcudacxx-config.cmake (found suitable version "1.8.1.0", minimum required is "1.8.0")
      -- Found Thrust: /tmp/pip-req-build-_2qrs2c6/build/temp.linux-x86_64-cpython-38/_deps/thrust-src/thrust/cmake/thrust-config.cmake (found version "2.2.0.0")
      -- Found CUB: /tmp/pip-req-build-_2qrs2c6/build/temp.linux-x86_64-cpython-38/_deps/thrust-src/dependencies/cub/cub/cmake/cub-config.cmake (found suitable version "2.2.0.0", minimum required is "2.2.0.0")
      -- CPM: adding package eigen@ (master)
      -- The C compiler identification is GNU 10.5.0
      -- Check for working C compiler: /usr/bin/gcc
      -- Check for working C compiler: /usr/bin/gcc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Performing Test standard_math_library_linked_to_automatically
      -- Performing Test standard_math_library_linked_to_automatically - Success
      -- Standard libraries to link to explicitly: none
      -- Performing Test COMPILER_SUPPORT_WERROR
      -- Performing Test COMPILER_SUPPORT_WERROR - Success
      -- Performing Test COMPILER_SUPPORT_pedantic
      -- Performing Test COMPILER_SUPPORT_pedantic - Success
      -- Performing Test COMPILER_SUPPORT_Wall
      -- Performing Test COMPILER_SUPPORT_Wall - Success
      -- Performing Test COMPILER_SUPPORT_Wextra
      -- Performing Test COMPILER_SUPPORT_Wextra - Success
      -- Performing Test COMPILER_SUPPORT_Wundef
      -- Performing Test COMPILER_SUPPORT_Wundef - Success
      -- Performing Test COMPILER_SUPPORT_Wcastalign
      -- Performing Test COMPILER_SUPPORT_Wcastalign - Success
      -- Performing Test COMPILER_SUPPORT_Wcharsubscripts
      -- Performing Test COMPILER_SUPPORT_Wcharsubscripts - Success
      -- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor
      -- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor - Success
      -- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs
      -- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs - Success
      -- Performing Test COMPILER_SUPPORT_Wpointerarith
      -- Performing Test COMPILER_SUPPORT_Wpointerarith - Success
      -- Performing Test COMPILER_SUPPORT_Wwritestrings
      -- Performing Test COMPILER_SUPPORT_Wwritestrings - Success
      -- Performing Test COMPILER_SUPPORT_Wformatsecurity
      -- Performing Test COMPILER_SUPPORT_Wformatsecurity - Success
      -- Performing Test COMPILER_SUPPORT_Wshorten64to32
      -- Performing Test COMPILER_SUPPORT_Wshorten64to32 - Failed
      -- Performing Test COMPILER_SUPPORT_Wlogicalop
      -- Performing Test COMPILER_SUPPORT_Wlogicalop - Success
      -- Performing Test COMPILER_SUPPORT_Wenumconversion
      -- Performing Test COMPILER_SUPPORT_Wenumconversion - Failed
      -- Performing Test COMPILER_SUPPORT_Wcpp11extensions
      -- Performing Test COMPILER_SUPPORT_Wcpp11extensions - Failed
      -- Performing Test COMPILER_SUPPORT_Wdoublepromotion
      -- Performing Test COMPILER_SUPPORT_Wdoublepromotion - Success
      -- Performing Test COMPILER_SUPPORT_Wshadow
      -- Performing Test COMPILER_SUPPORT_Wshadow - Success
      -- Performing Test COMPILER_SUPPORT_Wnopsabi
      -- Performing Test COMPILER_SUPPORT_Wnopsabi - Success
      -- Performing Test COMPILER_SUPPORT_Wnovariadicmacros
      -- Performing Test COMPILER_SUPPORT_Wnovariadicmacros - Success
      -- Performing Test COMPILER_SUPPORT_Wnolonglong
      -- Performing Test COMPILER_SUPPORT_Wnolonglong - Success
      -- Performing Test COMPILER_SUPPORT_fnochecknew
      -- Performing Test COMPILER_SUPPORT_fnochecknew - Success
      -- Performing Test COMPILER_SUPPORT_fnocommon
      -- Performing Test COMPILER_SUPPORT_fnocommon - Success
      -- Performing Test COMPILER_SUPPORT_fstrictaliasing
      -- Performing Test COMPILER_SUPPORT_fstrictaliasing - Success
      -- Performing Test COMPILER_SUPPORT_wd981
      -- Performing Test COMPILER_SUPPORT_wd981 - Failed
      -- Performing Test COMPILER_SUPPORT_wd2304
      -- Performing Test COMPILER_SUPPORT_wd2304 - Failed
      -- Performing Test COMPILER_SUPPORT_OPENMP
      -- Performing Test COMPILER_SUPPORT_OPENMP - Success
      -- The Fortran compiler identification is GNU 9.4.0
      -- Found unsuitable Qt version "" from NOTFOUND
      -- Qt4 not found, so disabling the mandelbrot and opengl demos
      -- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
      --
      -- Configured Eigen 3.4.90
      --
      -- CPM: adding package CLI11@ (main)
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Found OpenMP: TRUE (found version "4.5")
      Compiling without PyTorch support
      -- Configuring done
      CMake Error at CMakeLists.txt:83 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at CMakeLists.txt:88 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at build/temp.linux-x86_64-cpython-38/_deps/pybind11-src/tools/pybind11Tools.cmake:181 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      Call Stack (most recent call first):
        src/CMakeLists.txt:32 (pybind11_add_module)
      
      
      CMake Error at src/CMakeLists.txt:26 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at src/CMakeLists.txt:20 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at src/CMakeLists.txt:29 (add_executable):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at src/CMakeLists.txt:23 (add_library):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at test/CMakeLists.txt:7 (add_executable):
        CUDA_STANDARD is set to invalid value '17'
      
      
      CMake Error at test/CMakeLists.txt:16 (add_executable):
        CUDA_STANDARD is set to invalid value '17'
      
      
      -- Generating done
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-_2qrs2c6/setup.py", line 120, in <module>
          setup(
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/src/anaconda3/envs/emseg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-_2qrs2c6/setup.py", line 33, in run
          self.build_extension(ext)
        File "/tmp/pip-req-build-_2qrs2c6/setup.py", line 117, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/src/anaconda3/envs/emseg/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-_2qrs2c6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-_2qrs2c6/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=/src/anaconda3/envs/emseg/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for RAMA
  Running setup.py clean for RAMA
Failed to build RAMA
ERROR: Could not build wheels for RAMA, which is required to install pyproject.toml-based projects
```

**Comment by pawelswoboda** [comment]
Can you try out compiling the C++ version via

mkdir build && cd build
make ..
make

and give me the output? I suspect it might be some deprecated cuda code in one of our dependencies that we have not yet updated, but I will do so next week.

**Comment by liuyx599** [comment]
Okay, this is the output of c++ version:
```
(emseg) root@task:/src/RAMA-master/RAMA-master/build# cmake ..
-- The CXX compiler identification is GNU 10.5.0
-- The CUDA compiler identification is NVIDIA 11.3.109
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Downloading CPM.cmake to /src/RAMA-master/RAMA-master/build/cmake/CPM_0.34.0.cmake
-- CPM: adding package pybind11@ (master)
-- pybind11 v2.12.0 dev1
CMake Warning at build/_deps/pybind11-src/tools/pybind11Common.cmake:153 (message):
  USE -DCMAKE_CXX_STANDARD=17 instead of PYBIND11_CPP_STANDARD
Call Stack (most recent call first):
  build/_deps/pybind11-src/CMakeLists.txt:237 (include)


-- Found PythonInterp: /src/anaconda3/envs/emseg/bin/python (found suitable version "3.8.18", minimum required is "3.6") 
-- Found PythonLibs: /src/anaconda3/envs/emseg/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- CPM: adding package thrust@ (main)
-- Found libcudacxx: /src/RAMA-master/RAMA-master/build/_deps/thrust-src/dependencies/libcudacxx/lib/cmake/libcudacxx/libcudacxx-config.cmake (found suitable version "1.8.1.0", minimum required is "1.8.0") 
-- Found Thrust: /src/RAMA-master/RAMA-master/build/_deps/thrust-src/thrust/cmake/thrust-config.cmake (found version "2.2.0.0") 
-- Found CUB: /src/RAMA-master/RAMA-master/build/_deps/thrust-src/dependencies/cub/cub/cmake/cub-config.cmake (found suitable version "2.2.0.0", minimum required is "2.2.0.0") 
-- CPM: adding package eigen@ (master)
-- The C compiler identification is GNU 10.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test standard_math_library_linked_to_automatically
-- Performing Test standard_math_library_linked_to_automatically - Success
-- Standard libraries to link to explicitly: none
-- Performing Test COMPILER_SUPPORT_WERROR
-- Performing Test COMPILER_SUPPORT_WERROR - Success
-- Performing Test COMPILER_SUPPORT_pedantic
-- Performing Test COMPILER_SUPPORT_pedantic - Success
-- Performing Test COMPILER_SUPPORT_Wall
-- Performing Test COMPILER_SUPPORT_Wall - Success
-- Performing Test COMPILER_SUPPORT_Wextra
-- Performing Test COMPILER_SUPPORT_Wextra - Success
-- Performing Test COMPILER_SUPPORT_Wundef
-- Performing Test COMPILER_SUPPORT_Wundef - Success
-- Performing Test COMPILER_SUPPORT_Wcastalign
-- Performing Test COMPILER_SUPPORT_Wcastalign - Success
-- Performing Test COMPILER_SUPPORT_Wcharsubscripts
-- Performing Test COMPILER_SUPPORT_Wcharsubscripts - Success
-- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor
-- Performing Test COMPILER_SUPPORT_Wnonvirtualdtor - Success
-- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs
-- Performing Test COMPILER_SUPPORT_Wunusedlocaltypedefs - Success
-- Performing Test COMPILER_SUPPORT_Wpointerarith
-- Performing Test COMPILER_SUPPORT_Wpointerarith - Success
-- Performing Test COMPILER_SUPPORT_Wwritestrings
-- Performing Test COMPILER_SUPPORT_Wwritestrings - Success
-- Performing Test COMPILER_SUPPORT_Wformatsecurity
-- Performing Test COMPILER_SUPPORT_Wformatsecurity - Success
-- Performing Test COMPILER_SUPPORT_Wshorten64to32
-- Performing Test COMPILER_SUPPORT_Wshorten64to32 - Failed
-- Performing Test COMPILER_SUPPORT_Wlogicalop
-- Performing Test COMPILER_SUPPORT_Wlogicalop - Success
-- Performing Test COMPILER_SUPPORT_Wenumconversion
-- Performing Test COMPILER_SUPPORT_Wenumconversion - Failed
-- Performing Test COMPILER_SUPPORT_Wcpp11extensions
-- Performing Test COMPILER_SUPPORT_Wcpp11extensions - Failed
-- Performing Test COMPILER_SUPPORT_Wdoublepromotion
-- Performing Test COMPILER_SUPPORT_Wdoublepromotion - Success
-- Performing Test COMPILER_SUPPORT_Wshadow
-- Performing Test COMPILER_SUPPORT_Wshadow - Success
-- Performing Test COMPILER_SUPPORT_Wnopsabi
-- Performing Test COMPILER_SUPPORT_Wnopsabi - Success
-- Performing Test COMPILER_SUPPORT_Wnovariadicmacros
-- Performing Test COMPILER_SUPPORT_Wnovariadicmacros - Success
-- Performing Test COMPILER_SUPPORT_Wnolonglong
-- Performing Test COMPILER_SUPPORT_Wnolonglong - Success
-- Performing Test COMPILER_SUPPORT_fnochecknew
-- Performing Test COMPILER_SUPPORT_fnochecknew - Success
-- Performing Test COMPILER_SUPPORT_fnocommon
-- Performing Test COMPILER_SUPPORT_fnocommon - Success
-- Performing Test COMPILER_SUPPORT_fstrictaliasing
-- Performing Test COMPILER_SUPPORT_fstrictaliasing - Success
-- Performing Test COMPILER_SUPPORT_wd981
-- Performing Test COMPILER_SUPPORT_wd981 - Failed
-- Performing Test COMPILER_SUPPORT_wd2304
-- Performing Test COMPILER_SUPPORT_wd2304 - Failed
-- Performing Test COMPILER_SUPPORT_OPENMP
-- Performing Test COMPILER_SUPPORT_OPENMP - Success
-- The Fortran compiler identification is GNU 9.4.0
-- Found unsuitable Qt version "" from NOTFOUND
-- Qt4 not found, so disabling the mandelbrot and opengl demos
-- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
-- 
-- Configured Eigen 3.4.90
-- 
-- CPM: adding package CLI11@ (main)
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
Compiling without PyTorch support
-- Configuring done
CMake Error at CMakeLists.txt:83 (add_library):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at CMakeLists.txt:88 (add_library):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at src/CMakeLists.txt:20 (add_library):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at src/CMakeLists.txt:26 (add_library):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at src/CMakeLists.txt:29 (add_executable):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at src/CMakeLists.txt:23 (add_library):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at test/CMakeLists.txt:7 (add_executable):
  CUDA_STANDARD is set to invalid value '17'


CMake Error at test/CMakeLists.txt:16 (add_executable):
  CUDA_STANDARD is set to invalid value '17'


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by aabbas90** [comment]
Possibly your cmake version is [old](https://github.com/PaddlePaddle/Paddle/issues/54822#issuecomment-1602734808). Could you please try 3.26 or above.

**Comment by liuyx599** [comment]
Very excited that it seems to have worked after a long wait.
```
Created wheel for RAMA: filename=RAMA-0.0.8-cp38-cp38-linux_x86_64.whl size=8402682 sha256=31dfb302b4dea68ee680e17178db80a014fef15ec8f458347393fd347a5fee20
Stored in directory: /tmp/pip-ephem-wheel-cache-xs8g9c63/wheels/22/0e/08/dc1db9b70422dd9e1ad4c9fb01f1f359af2a3d6dc3f7dd2d0f
Successfully built RAMA
Installing collected packages: RAMA
Successfully installed RAMA-0.0.8
```
But at the same time, I'd like to ask if there's a way to install offline, or if there's a way to save it offline now that I've successfully installed it, because I've had errors like ssl timeout when installing with git before (maybe it's a firewall issue), yet I'm running the program in question on a cluster of servers, and it seems to be a frowned upon thing to use proxies.
